#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/crontabs

## root
# if crontabs do not exist in config
if [[ ! -f /config/crontabs/root ]]; then
    # copy crontab from system
    if crontab -l -u root; then
        crontab -l -u root >/config/crontabs/root
    fi

    # if crontabs still do not exist in config (were not copied from system)
    # copy crontab from included defaults
    if [[ ! -f /config/crontabs/root ]]; then
        cp /etc/crontabs/root /config/crontabs/
        echo "Copied default crontabs to /config/crontabs/root"
    fi
fi
# set permissions and import user crontabs
lsiown root:root /config/crontabs/root
crontab -u root /config/crontabs/root
